insert into matters (id, name) values (1, 'Português')
insert into matters (id, name) values (2, 'Matemática')
insert into matters (id, name) values (3, 'Informática Básica')
insert into matters (id, name) values (4, 'Atualidades')
insert into matters (id, name) values (5, 'Informática Avançada')

insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (1, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (2, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (3, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (4, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (5, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (6, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (7, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (8, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (9, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (10, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (11, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (12, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (13, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (14, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (15, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (16, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (17, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (18, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (19, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (20, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (21, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (22, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (23, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (24, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (25, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (26, 'Front Content 1', 'Back Content 1', 1, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (27, 'Front Content 1', 'Back Content 1', 2, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (28, 'Front Content 1', 'Back Content 1', 3, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (29, 'Front Content 1', 'Back Content 1', 4, '2023-11-19', 0)
insert into flashcards (id, front, back, id_matter, dateshow, daysshow) values (30, 'Front Content 1', 'Back Content 1', 5, '2023-11-19', 0)